server:
  port: 8081

spring:
  application:
    name: deal

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
    drop-first: false

  datasource:
    url: jdbc:postgresql://localhost:5432/bank-app
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    ru.neoflex.deal: DEBUG
    org.springframework.security: DEBUG

deal:
  service:
    base-url: http://localhost:8080

  app:
    public-url: http://localhost:8084/deal/document/

  topics:
    finish-registration: finish-registration
    create-documents: create-documents
    send-documents: send-documents
    send-ses: send-ses
    credit-issued: credit-issued
    statement-denied: statement-denied